### ISSUE TITLE
Difficulty to see diff colors in Redmine 4.x

### ISSUE THREAD

**Issue by phimage** [mrliptontea/PurpleMine2#112]
Hi,
on redmine 4, (using chrome) I have some difficulties to see diff on
- http(s)://`redminehost`/journals/`issue id`/diff?detail_id=`detail id`
- http(s)://`redminehost`/`projects path`/wiki/Releases/`version id`/diff

There is too much transparence (alpha)

---

I see some span with class diff_in and diff_out
```html
<span class="diff_in">text</span>
```
The colors come from css diff_in and diff_out
```css
.diff_in {
	background: rgba(186, 253, 208, 0.4)
}
```

The following css is not used
```css
.diff_in span {
	background: #bafdd0
}
```
It could work with some html like that, but unfortunately redmine 4 do not add other html nodes 
```html
<diff class="diff_in"><span>text</span></div>
```

I think it could be fixed by generating with sass instead
```css
span.diff_in {
	background: #bafdd0
}
```
but maybe there is some difference between redmine versions
