### ISSUE TITLE
Broken spacing for headers on roadmap pages

### ISSUE THREAD

**Issue by ilpssun** [mrliptontea/PurpleMine2#132]
The spacing after `h2` and `h3` on wiki pages that are displayed as part of the roadmap is too small.  To fix that, I suggest you remove `display: inline` in `_elements.scss:599`:

```scss
  h2,
  h3 {
    /* display: inline; fix roadmap layout */
    padding-right: 0;
  }
```
