### ISSUE TITLE
Possible changes to stylesheet...

### ISSUE THREAD

**Issue by MatthewPaulGithub** [mrliptontea/PurpleMine2#181]
I just converted over to Purplemine2 and I think it's one of the best (if not THE best) modern looking theme. Very nice and thanks for doing this. In the spirit of open source sharing, I did make a few changes, but I am honestly garbage at CSS, so I didn't want to risk forking and messing stuff up. So instead I thought I'd post a couple of ideas that you, an actual expert, could look at and see if you want to use them or just throw away. So here goes...

1. Theme colors - right at the top I added -
    ```css
    :root {
        --themecolor: black;
        --topcolor: steelblue;
    }
    ```
    ...and then did a change all for background to use these rather than the specific purple. So that way it's v easy to change to blackmine, greenmine, bluemine etc. like this -

    ```css
    background: var(--themecolor);
    ```
    (topcolor is used for flyouts) like -
    ```css
    #top-menu {
        background: var(--topcolor);
    }
    ```

2. Changed some flyout stuff to make it look better for me. I have plugins to add content to the sidebar/flyout so I needed a wider flyout and smaller text.  Maybe this is just me???  But I wanted all the awesome goodness of your theme on responsive so I spent quite a lot of time tuning it. My phone is large format iphoneX but it should fit smaller phones too -

    ```scss
    #sidebar {
        flex: 0 0 299px; /* mp changed from 229px which was too small */
        order: -1;
        font-size: small; /* mp added because font was too large for sidebar */
    }

    #main #sidebar {
        padding: 20px 10px   /* mp changed from 20px 20px I think */
    }

    #sidebar ul:nth-child(n) {
        margin: 0 0 10px;
        padding: 0;
        margin-right: -10px    /* mp changed from -20px I think */
    }

    #sidebar ul:not(.watchers) li>a:not(.icon-only) {
        display: inline-block;    /* mp changed from block so that icons on same line */ 
        padding: 3px 6px;   /*mp changed from ?? ?? */
        border: 1px solid transparent;
        border-left-width: 3px;   /* mp changed? */
        border-radius: 4px 0 0 4px
    }

    #sidebar div.page-tree .page-tree__list .page-tree__list summary {
        padding-left: 10px /* mp was 28 */
    }

    body .flyout-menu ul li:nth-child(n) a {
        height: auto;
        padding: 3px 6px;  /* mp changed from 10px 16px */
        line-height: 1.428571429;
        display: inline-block; /* mp added */
    }
    ```

3. IMPORTANT - again, this might just be me??  But when I do an EDIT on an issue, all looks good but the jstoolbar for the comment text is getting wiped out.  So this fixed that. Not sure why. As I say I'm pretty hopeless...
    ```scss
    div.jstElements {
        line-height: normal;
        position: relative;  /* mp v important this fixed missing edit icons in jstoolbar */
    }
    ```

4. Buttons had a lot of padding on the left I think which maybe was causing a problem with them running over onto next line??  So I took some padding out to fit them on one line...

    ```scss
    body #query_form_with_buttons>.contextual a.icon {
        padding-left: 10px; /* mp was 28 */
        background-position: 8px 50%
    }
    ```

I think that's it. Again, please feel free to just throw this in the trash if you like, but my screens are looking pretty nice thanks to your theme so I wanted to at least give you that info in case any of it is helpful.

Thanks again!

Matthew Paul
